# Toml 測試

title = "TOML Example"

# owenor
[owenor]
name = "Tom"
account = "test123"

# rpc_server
[rpc_server]
server = "127.0.0.1"
port = "8756"
connection_max = 5000
enabled = true

# servers
[servers.alpha]
ip = "10.0.0.1"
dc = "eqdc10"
[servers.beta]
ip = "10.0.0.2"
dc = "eqdc10"

[clients]
data = [["gamma","delta"],["1","2"]]